packages:
  - '@nightcord/*'

catalog:
  '@cloudflare/workers-types': ^4.20260207.0
  '@fontsource-variable/eb-garamond': ^5.2.7
  '@inlang/paraglide-js': ^2.10.0
  '@libsql/client': ^0.17.0
  '@sveltejs/adapter-cloudflare': ^7.2.6
  '@sveltejs/kit': ^2.50.2
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^24.10.11
  '@types/three': ^0.182.0
  animejs: ^4.3.5
  bits-ui: ^2.15.5
  clsx: ^2.1.1
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  ip-address: ^10.1.0
  lucide-svelte: ^0.563.0
  openai: ^6.18.0
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.4.1
  prettier-plugin-tailwindcss: ^0.7.2
  svelte: ^5.50.0
  svelte-check: ^4.3.6
  svelte-sonner: ^1.0.7
  svelte-turnstile: ^0.11.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  three: ^0.182.0
  turnstile-types: ^1.2.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-devtools-json: ^1.0.0
  wrangler: ^4.63.0
  zod: ^4.3.6

catalogMode: strict

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  three: patches/three.patch
