packages:
  - '@nightcord/*'

catalog:
  '@cloudflare/workers-types': ^4.20250906.0
  '@inlang/paraglide-js': ^2.0.0
  '@sveltejs/adapter-cloudflare': ^7.0.0
  '@sveltejs/kit': ^2.22.0
  '@sveltejs/vite-plugin-svelte': ^6.0.0
  '@tailwindcss/vite': ^4.0.0
  '@types/node': ^22.18.1
  bits-ui: ^2.9.6
  drizzle-kit: ^0.30.2
  drizzle-orm: ^0.40.0
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  prettier-plugin-tailwindcss: ^0.6.14
  svelte: ^5.0.0
  svelte-check: ^4.0.0
  svelte-turnstile: ^0.11.0
  tailwindcss: ^4.0.0
  typescript: ^5.0.0
  vite: ^7.0.4
  vite-plugin-devtools-json: ^1.0.0
  wrangler: ^4.34.0
  zod: ^4.1.5

catalogMode: strict
