packages:
  - '@nightcord/*'

catalog:
  '@cloudflare/workers-types': ^4.20250906.0
  '@inlang/paraglide-js': ^2.2.0
  '@sveltejs/adapter-cloudflare': ^7.2.3
  '@sveltejs/kit': ^2.37.1
  '@sveltejs/vite-plugin-svelte': ^6.1.4
  '@tailwindcss/vite': ^4.1.13
  '@types/node': ^22.18.1
  bits-ui: ^2.9.6
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  prettier-plugin-tailwindcss: ^0.6.14
  svelte: ^5.38.7
  svelte-check: ^4.3.1
  svelte-turnstile: ^0.11.0
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vite: ^7.1.4
  vite-plugin-devtools-json: ^1.0.0
  wrangler: ^4.34.0
  zod: ^4.1.5

catalogMode: strict

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
