name = "nightcord-at-admin"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-05"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "admin.nightcord.at"
custom_domain = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "nightcord_at_25"
database_id = "49cea6dc-18ac-429f-91de-01fd9e8649fb"
migrations_dir = "../shared/drizzle/"

[observability]
enabled = true
